INSERT INTO
	@table@ (header, expected, unexpected, exact, information_link, information_description, deprecated, deprecated_alternative_name, deprecated_alternative_link)
VALUES
	('strict-transport-security','["max-age >= 31536000"]',NULL,'0','https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security','The HTTP Strict-Transport-Security response header (often abbreviated as HSTS) lets a web site tell browsers that it should only be accessed using HTTPS, instead of using HTTP.','0',NULL,NULL),
	('referrer-policy', '["no-referrer","no-referrer-when-downgrade","origin","origin-when-cross-origin","same-origin","strict-origin","strict-origin-when-cross-origin"]', NULL, '0', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy', 'The Referrer-Policy HTTP header controls how much referrer information (sent via the Referer header) should be included with requests. Aside from the HTTP header, you can set this policy in HTML.', '0', NULL, NULL),
	('permissions-policy', '["="]', NULL, '0', 'https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md', 'The Permissions-Policy specification defines a mechanism that allows developers to selectively enable and disable use of various browser features and APIs.', '0', NULL, NULL),
	('content-security-policy', '["default-src \'none\'"]', '["unsafe-inline", "unsafe-eval"]', '0', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP', 'Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement to distribution of malware.', '0', NULL, NULL),
	('x-frame-options', '["deny", "sameorigin", "allow-from"]', NULL, '1', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options', 'The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page in a <frame>, <iframe>, <embed> or <object>. Sites can use this to avoid click-jacking attacks, by ensuring that their content is not embedded into other sites.', '0', NULL, NULL),
	('x-content-type-options', '["nosniff"]', NULL, '1', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options', 'The X-Content-Type-Options response HTTP header is a marker used by the server to indicate that the MIME types advertised in the Content-Type headers should not be changed and be followed.', '0', NULL, NULL),
	('x-xss-protection', '["0", "1"]', NULL, '0', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection', 'The HTTP X-XSS-Protection response header is a feature of Internet Explorer, Chrome and Safari that stops pages from loading when they detect reflected cross-site scripting (XSS) attacks. Some security scanners look for this header. Some browsers may still support this header.', '1', 'Content Security Policy', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy')
